language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer self-update
- composer install
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build
- mkdir build/coverage
- phpunit -c app/
after_success:
- php vendor/bin/coveralls -v -c .coveralls.yml
notifications:
  email:
    recipients:
    - travis@josecelano.email
    on_success: change
  slack:
    secure: pPYBA4IPveryk2rpChYDFP9WqN4d9fqaY+JKC4DDpSAwrbgzDBIfzZzu8xJWRP6M5cTn4mFAUSGpbhYxEx3sYAcHPYa6rt+4jreS+3/rdoi+Vl/MCmrxrG89tLsX/4cCEEA0aI+LhUZthtjwpQl2F16l/2g86560TL5zp73zGqqCL/pox3woN3Zk++1IGQU5foh0Ccz9SSCcWh2Q6abdWN09sH7085I2q8ZmRsET66cPF0J4VUAvaYlp/xkym5/9M7KkM0+m0LK7qhzoGX/7fRFKZrLQb5IWp9EnHEeYQOVQd17FLu9d83goesbGvxPrPFRD2CzYzFGRGg/4nvQP03t3c6NR0ridjWWjgcOUTtukqTL8E3YKB2JrbJhzAD1j+WE5sSxzCszG30NVheFPP7qr1uukSu7Un5A+pOJRJ03jqhyWZZBM4J65RJc3zNTCZiaFZ+dbK6B8WmOslsG23bQg9LWipyIsVHUmiktCHa+HE3gwfeiJECFlnjuh/WiyWvY+dueh3SzI2eT1aX+D0g7aMa/Ohrn6t1RBXmyU3CsNTt6dMqGLafx2bjtuTfz2O9SafseRk+NpHPOZ8QFfZQ83s/2nI+el26PpmZb2ehslM/92c6fl/hs16Aet8oBihWVzGoFdlv3vzzXIWblvSX1wMzV1ydoWbwoHhIPbZRA=
deploy:
  provider: heroku
  api_key:
    secure: cQDyw0GMwleVn1QwOUl0ru6m76VYipgjvyLqP+y6HrDx+XUHQiXkR4LZdtE+xVHLSDyEj8CookTcxj8Z7AFYW4+gVR70IC0we56cY0y2hRDsABstB3Sr9XZxlqTOyS4mjHy5sV6ZSTpTxGFgGQ7wHAqL4bj7hBk6oVWhhgz3Jd2rsPyVwLP/PLfBTGU1UL1NY936oBFIXPSPvcP/HSvr+TInBc9asiCdZ106Rb7rB2YPp3njqaYjs1pmydVKptgqbDOAUHMb+B2csebrk0pUMNc8KMYIaTZRIjxa8b25duwOewFT1JGNc8HSC95W8H0H16ZW97pG4c+xYKhJEX/Ah1lyZe1CfT5f6492wXV20ccy0I2pZuC65WHIWSgd4OGXRiMQGv9o4fl4SaYfobJup13r5bJTpVzMANxRoHWUehDUMrr9rf2yaD+M9S5gR5waZ64lX2lp7XTVlQwGYAUm9fv0nQ/N6DEeBkm25i0MNSAQzAZt3cLqnCxSSws6zmFJPX47LCHzV4Yh+VrJReXgxIaDOIzDZuHU7F4UnlpnLi2xTnOLzZqWwGOx1kWW93J/uESFn4MXpe6skmv2ZTVV+zJex7fiHzcZ7x38/CoM7kTRdfFjp7k7xMsLDohPt4Mf8Fp9eKlQ4hSEEqLr72fULvWAi+4k9V300HhaTcNjOvY=
  app: php-wallet-sample
  on:
    repo: blockcypher/php-wallet-sample
    php: 5.6
