language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer self-update
- composer install
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build
- mkdir build/coverage
- phpunit -c app/
after_success:
- php vendor/bin/coveralls -v -c .coveralls.yml
notifications:
  email:
    recipients:
    - travis@josecelano.email
    on_success: change
deploy:
  provider: heroku
  api_key:
    secure: gc85IDZ04VkkpsYkp84A04iSlKTNhr90mpZA1DdFojg+ZcSXcwqqq+juiM2XeAoIkje5FRYbvuvAdOz0SRs1m8khG70xv93DgeEN+9DUXbpZJkr1BDmd1zyG5t5z4D8W0GnkybRTdZq04YGTW0MCMSZQqKnbmnG11Jf5bwVohvfC+QBC8aiX0fQN2V6JZiCWVNmWyBjUQ1Rq7x8J7twMIs4/7mpLsrnmgbZdvPyRukn1IWcxrK5Pfq/VNlKaDhdrjplavXF7i8PEjIC+FGJYnORyhYTwkQ0wYi4bPCfW1ZPREckpxuNwwfhYTQx6486fPSs2HzhfY6rn+OhgwQveZY9ircG8xKd7yfwxDQMMpIR0dZrjPIoEwqnmDALeho1xS/1vJBwD/CDMRm2WVS9gxmP1b6exi+pZvfM5o35SGCOMEuvqpIHTNwy0cMphEtPJkrd4eQatIawuZ40XhKZzQeBAqJYtE8CX/lnrQc/aPt/gmT/fX3W6HrubNuagdo4PGzQW/F2ei7fDQdW9LhlVNxaXl0Vp3mEtle330XYrTGcWLaO1Xtk1mPsdOMpNcv7nW5UXpmSAtna69lvKm7Ahsqu4zdR5yhdXXBXeBvLCsU6YoXZQCSgj1WEibcK1b/rPQp+xm1HOEq6B0bqDyYLUtNWHlQ71/Xce0YXc6sbvXPE=
  app: php-wallet-sample
  on:
    repo: blockcypher/php-wallet-sample