bc_app_wallet_account.index:
    pattern:  /accounts
    defaults: { _controller: "bc_app_wallet_account.index_controller" }
    requirements: { _method: get }

bc_app_wallet_account.new:
    pattern:  /accounts/new
    defaults: { _controller: "bc_app_wallet_account.show_new_controller" }

bc_app_wallet_account.create:
    pattern:  /accounts
    defaults: { _controller: "bc_app_wallet_account.create_controller" }
    requirements: { _method: post }