parameters:

    # controllers

    bc_app_wallet_account.index_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Account\Index

    # sercice facades

    bc_app_wallet_account.account_service_facade.class: BlockCypher\AppWallet\Presentation\Facade\Internal\AccountServiceFacadeImpl
    
    # services
    
    bc_app_wallet_account.account_service.class: BlockCypher\AppWallet\App\Service\Internal\AccountServiceImpl

    # repositories

    bc_app_wallet_account.account_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelAccountRepository

services:

    # controllers

    bc_app_wallet_account.index_controller:
        class: %bc_app_wallet_account.index_controller.class%
        arguments:
         - @templating
         - @translator
         - @bc_app_wallet_account.account_service_facade

    # sercice facades

    bc_app_wallet_account.account_service_facade:
        class: %bc_app_wallet_account.account_service_facade.class%
        arguments:
          - @bc_app_wallet_account.account_service
          
    # services
    
    bc_app_wallet_account.account_service:
        class: %bc_app_wallet_account.account_service.class%
        arguments:
          - @bc_app_wallet_account.account_repository

    # repositories

    bc_app_wallet_account.account_repository:
        class: %bc_app_wallet_account.account_repository.class%
        arguments:
          - @block_cypher_app_common_infrastructure_app_common.clock