parameters:

    # controllers

    bc_app_wallet_account.index_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Account\Index
    bc_app_wallet_account.show_new_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Account\ShowNew
    bc_app_wallet_account.create_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Account\Create

    # sercice facades

    bc_app_wallet_account.account_service_facade.class: BlockCypher\AppWallet\Presentation\Facade\Internal\AccountServiceFacadeImpl
    
    # services
    
    bc_app_wallet_account.account_service.class: BlockCypher\AppWallet\App\Service\Internal\AccountServiceImpl

    # repositories

    bc_app_wallet_account.encrypted_account_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelEncryptedAccountRepository
    bc_app_wallet_account.account_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelAccountRepository

    # fixtures loaders

    bc_app_wallet_account.account_data_loader.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\DataFixtures\LoadAccountData

    # command handlers

    bc_app_wallet_account.create_account_command_handler.class: BlockCypher\AppWallet\App\Command\CreateAccountCommandHandler

    # form factories

    bc_app_wallet_account.account_form_factory.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form\Account\AccountFormFactory


services:

    # controllers

    bc_app_wallet_account.index_controller:
        class: %bc_app_wallet_account.index_controller.class%
        arguments:
         - @templating
         - @translator
         - @bc_app_wallet_account.account_service_facade

    bc_app_wallet_account.show_new_controller:
        class: %bc_app_wallet_account.show_new_controller.class%
        arguments:
         - @templating
         - @translator
         - @bc_app_wallet_account.account_form_factory

    bc_app_wallet_account.create_controller:
        class: %bc_app_wallet_account.create_controller.class%
        arguments:
         - @templating
         - @translator
         - @router
         - @bc_app_wallet_account.account_form_factory
         - @command_bus

    # sercice facades

    bc_app_wallet_account.account_service_facade:
        class: %bc_app_wallet_account.account_service_facade.class%
        arguments:
          - @bc_app_wallet_account.account_service
          
    # services
    
    bc_app_wallet_account.account_service:
        class: %bc_app_wallet_account.account_service.class%
        arguments:
          - @bc_app_wallet_account.account_repository

    # repositories

    bc_app_wallet_account.encrypted_account_repository:
        class: %bc_app_wallet_account.encrypted_account_repository.class%
        arguments:
          - @bc_app_common_infrastructure_app_common.clock

    bc_app_wallet_account.account_repository:
        class: %bc_app_wallet_account.account_repository.class%
        arguments:
          - @bc_app_wallet_account.encrypted_account_repository
          - @bc_app_wallet_wallet.wallet_repository
          - @bc_app_common_infrastructure_app_common.encryptor
          - @bc_app_common_infrastructure_app_common.encryptor

    # fixtures loaders

    bc_app_wallet_account.account_data_loader:
        class: %bc_app_wallet_account.account_data_loader.class%
        arguments:
          - @bc_app_common_infrastructure_app_common.clock
          - @bc_app_wallet_account.account_repository

    # command handlers

    bc_app_wallet_account.create_account_command_handler:
        class: %bc_app_wallet_account.create_account_command_handler.class%
        arguments:
            - @bc_app_wallet_account.account_repository
            - @bc_app_wallet_wallet.wallet_repository
            - @bc_app_common_blockcypher.wallet_service
            - @bc_app_common_infrastructure_app_common.clock
        tags:
            - { name: command_handler, handles: bc_app_wallet_account_create_account }

    # form factory

    bc_app_wallet_account.account_form_factory:
        class: "%bc_app_wallet_account.account_form_factory.class%"
        public: false
        arguments:
            - "@form.factory"
            - "@router"
            - "@translator"
