parameters:

    # repositories

    bc_app_wallet_wallet.wallet_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelWalletRepository

services:

    # repositories

    bc_app_wallet_wallet.wallet_repository:
        class: %bc_app_wallet_wallet.wallet_repository.class%
        arguments:
          - @block_cypher_app_common_infrastructure_app_common.clock
          - @bc_app_common_blockcypher.wallet_service