parameters:

    # repositories

    bc_app_wallet_wallet.encrypted_wallet_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelEncryptedWalletRepository
    bc_app_wallet_wallet.wallet_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelWalletRepository

    # fixtures loaders

    bc_app_wallet_wallet.wallet_data_loader.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\DataFixtures\LoadWalletData

services:

    # repositories

    bc_app_wallet_wallet.encrypted_wallet_repository:
        class: %bc_app_wallet_wallet.encrypted_wallet_repository.class%
        arguments:
          - @bc_app_common_infrastructure_app_common.clock
          - @bc_app_common_blockcypher.wallet_service

    bc_app_wallet_wallet.wallet_repository:
        class: %bc_app_wallet_wallet.wallet_repository.class%
        arguments:
          - @bc_app_wallet_wallet.encrypted_wallet_repository
          - @bc_app_common_infrastructure_app_common.encryptor
          - @bc_app_common_infrastructure_app_common.encryptor

    # fixtures loaders

    bc_app_wallet_wallet.wallet_data_loader:
        class: %bc_app_wallet_wallet.wallet_data_loader.class%
        arguments:
          - @bc_app_common_infrastructure_app_common.clock
          - @bc_app_wallet_wallet.wallet_repository
          - @bc_app_common_blockcypher.wallet_service